class ChatState:
    enter_password = 'enter-password'
    main_page = 'main-page'
    send_email = 'send-email'
    contragents = 'contragents'
    add_agent_name = 'add_agent_name'
    add_agent_email = 'add_agent_email'
    delete_agent = 'delete_agent'
    redact_agent = 'redact_agent'
    redact_agent_username='redact_agent_username'
    redact_agent_email='redact_agent_email'
    change_letter_title='change_letter_title'
    change_letter_text='change_letter_text'
    send_test_email='send_test_email'

